# Generated by Django 6.0.4 on 2026-04-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sample_type', models.CharField(blank=True, max_length=100)),
                ('turnaround_hours', models.PositiveIntegerField(default=24)),
                ('is_home_collection', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'mf_lab_tests',
            },
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_home_collection', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labs.labtest')),
            ],
            options={
                'db_table': 'mf_lab_bookings',
            },
        ),
    ]
