# Generated by Django 3.1.12 on 2026-05-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('appointment_type', models.CharField(choices=[('In-Person', 'In-Person'), ('Online', 'Online'), ('Phone', 'Phone')], max_length=20)),
                ('reason_for_visit', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-Show', 'No-Show')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('services', models.JSONField(default=list)),
                ('total_amount', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('tax', models.FloatField(default=0.0)),
                ('payable_amount', models.FloatField()),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('Online Transfer', 'Online Transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], max_length=20)),
                ('paid_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('qualifications', models.JSONField(default=list)),
                ('experience_years', models.IntegerField(null=True)),
                ('consultation_fee', models.FloatField()),
                ('available_days', models.JSONField(default=list)),
                ('working_hours', models.JSONField(null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.URLField(blank=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.JSONField()),
                ('logo', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('specialties', models.JSONField(default=list)),
                ('bed_count', models.IntegerField(null=True)),
                ('ambulance_available', models.BooleanField(default=True)),
                ('emergency_services', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('working_hours', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('test_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('test_date', models.DateField(null=True)),
                ('result_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('result', models.JSONField(null=True)),
                ('report_file', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(auto_now_add=True)),
                ('visit_type', models.CharField(blank=True, max_length=50)),
                ('symptoms', models.JSONField(default=list)),
                ('diagnosis', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('vital_signs', models.JSONField(null=True)),
                ('follow_up_date', models.DateField(null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('address', models.JSONField(null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('medical_conditions', models.JSONField(default=list)),
                ('allergies', models.JSONField(default=list)),
                ('medications', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, unique=True)),
                ('medicine_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('generic_name', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Other', 'Other')], max_length=20)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='api_patient_email_b6d297_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='api_patient_phone_9d1c6b_idx'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doctor'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name'], name='api_hospita_name_c73516_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['email'], name='api_hospita_email_215886_idx'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='billing',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['medicine_name'], name='api_pharmac_medicin_eddb68_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['medicine_code'], name='api_pharmac_medicin_e9fd04_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['hospital', 'medicine_name'], name='api_pharmac_hospita_c6d4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['patient', 'record_date'], name='api_medical_patient_11ab39_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['hospital', 'record_date'], name='api_medical_hospita_b76f27_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['patient', 'test_date'], name='api_labtest_patient_6ff0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status'], name='api_labtest_status_08ddc9_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['email'], name='api_doctor_email_dbb22c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='api_doctor_special_a2cf69_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['hospital', 'specialization'], name='api_doctor_hospita_045fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['invoice_number'], name='api_billing_invoice_cc3fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['patient', 'invoice_date'], name='api_billing_patient_75f230_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['payment_status'], name='api_billing_payment_96b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='api_appoint_patient_0c9a79_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='api_appoint_doctor__9124cf_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='api_appoint_status_323c16_idx'),
        ),
    ]
