# Generated by Django 6.0.4 on 2026-04-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('featured_listing', 'Featured Hospital Listing'), ('homepage_banner', 'Homepage Banner'), ('search_boost', 'Search Boost'), ('category_sponsor', 'Category Sponsor')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('target_url', models.URLField(blank=True)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=10)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ads', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'mf_advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=4, default=0.5, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page', models.CharField(blank=True, max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_logs', to='monetization.hospitaladvertisement')),
            ],
            options={
                'db_table': 'mf_ad_impressions',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic — Free'), ('professional', 'Professional — ৳5,000/mo'), ('enterprise', 'Enterprise — ৳15,000/mo')], default='basic', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'mf_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('appointment', 'Appointment'), ('lab_booking', 'Lab Booking'), ('pharmacy', 'Pharmacy Order')], db_index=True, max_length=15)),
                ('source_ref', models.CharField(max_length=50)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=10)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'mf_commission_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='mf_commissi_hospita_8d42c8_idx'), models.Index(fields=['source_type', 'created_at'], name='mf_commissi_source__4f0ce1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hospitaladvertisement',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='mf_advertis_status_1103eb_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaladvertisement',
            index=models.Index(fields=['hospital', 'status'], name='mf_advertis_hospita_d5b749_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['ad', 'timestamp'], name='mf_ad_impre_ad_id_da5947_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['hospital', 'is_active'], name='mf_subscrip_hospita_2a46c1_idx'),
        ),
    ]
