# Generated by Django 4.2.20 on 2026-05-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='mf_email_ot_email_db8c2c_idx',
            old_name='mf_email_otp_email_is_used_idx',
        ),
    ]
