# Generated by Django 3.1.12 on 2026-05-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('Blood', 'Blood'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets'), ('Other', 'Other')], max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('donation_date', models.DateField()),
                ('quantity_ml', models.IntegerField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.patient')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'donation_date'], name='donation_do_donor_i_e31ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['hospital', 'donation_date'], name='donation_do_hospita_75b8b6_idx'),
        ),
    ]
